# Generated by Django 5.0 on 2024-02-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='instructor',
        ),
    ]
