# Generated by Django 5.0 on 2024-02-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_instructor_yt_link'),
        ('events', '0002_remove_event_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='instructor',
            field=models.ManyToManyField(blank=True, to='challenges.instructor'),
        ),
    ]
