# Generated by Django 5.0 on 2024-03-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(default='https://img.freepik.com/free-photo/painting-mountain-lake-with-mountain-background_188544-9126.jpg', verbose_name='Link to the image'),
            preserve_default=False,
        ),
    ]
