# Generated by Django 5.0 on 2023-12-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='activation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
