# Generated by Django 5.0 on 2024-01-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_is_active'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.event'),
        ),
    ]
