# Generated by Django 5.0 on 2024-01-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
