# Generated by Django 5.0 on 2024-01-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_myuser_auth_provider'),
        ('prizes', '0002_badge_medal'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='medals',
            field=models.ManyToManyField(blank=True, to='prizes.medal'),
        ),
    ]
