# Generated by Django 5.0 on 2024-01-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_myuser_medals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='born_year',
        ),
    ]
