# Generated by Django 5.0 on 2024-01-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_myuser_born_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='born_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
