# Generated by Django 5.0 on 2023-12-15 15:33

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHIW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('text_left_side', ckeditor.fields.RichTextField()),
                ('text_down_side', ckeditor.fields.RichTextField()),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Mental HIW',
                'verbose_name_plural': 'Mental HIWs',
            },
        ),
        migrations.CreateModel(
            name='PhysicalHIW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('text_left_side', ckeditor.fields.RichTextField()),
                ('text_down_side', ckeditor.fields.RichTextField()),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Physical HIW',
                'verbose_name_plural': 'Physical HIWs',
            },
        ),
        migrations.CreateModel(
            name='PrizesHIW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('text_left_side', ckeditor.fields.RichTextField()),
                ('text_down_side', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Prizes HIW',
                'verbose_name_plural': 'Prizes HIWs',
            },
        ),
        migrations.CreateModel(
            name='SocialHIW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('text_left_side', ckeditor.fields.RichTextField()),
                ('text_down_side', ckeditor.fields.RichTextField()),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Social HIW',
                'verbose_name_plural': 'Social HIWs',
            },
        ),
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mental_hiw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='how_it_works.mentalhiw')),
                ('physical_hiw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='how_it_works.physicalhiw')),
                ('prizes_hiw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='how_it_works.prizeshiw')),
                ('social_hiw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='how_it_works.socialhiw')),
            ],
            options={
                'verbose_name': 'How It Works',
                'verbose_name_plural': 'How It Works',
            },
        ),
    ]
