# Generated by Django 5.0 on 2023-12-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('how_it_works', '0002_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentalhiw',
            old_name='video',
            new_name='video_link',
        ),
        migrations.RenameField(
            model_name='physicalhiw',
            old_name='video',
            new_name='video_link',
        ),
        migrations.RenameField(
            model_name='prizeshiw',
            old_name='video',
            new_name='video_link',
        ),
        migrations.RenameField(
            model_name='socialhiw',
            old_name='video',
            new_name='video_link',
        ),
    ]
