# Generated by Django 5.0 on 2024-02-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('how_it_works', '0003_rename_video_mentalhiw_video_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howitworks',
            name='mental_hiw',
        ),
        migrations.RemoveField(
            model_name='howitworks',
            name='physical_hiw',
        ),
        migrations.RemoveField(
            model_name='howitworks',
            name='prizes_hiw',
        ),
        migrations.RemoveField(
            model_name='howitworks',
            name='social_hiw',
        ),
        migrations.DeleteModel(
            name='MentalHIW',
        ),
        migrations.DeleteModel(
            name='PhysicalHIW',
        ),
        migrations.DeleteModel(
            name='PrizesHIW',
        ),
        migrations.DeleteModel(
            name='HowItWorks',
        ),
        migrations.DeleteModel(
            name='SocialHIW',
        ),
    ]
