# Generated by Django 5.0 on 2024-02-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_it_works', '0004_remove_howitworks_mental_hiw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_link', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'How It Works',
                'verbose_name_plural': 'How It Works',
            },
        ),
        migrations.CreateModel(
            name='MentalHIW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_link', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Mental HIW',
                'verbose_name_plural': 'Mental HIWs',
            },
        ),
        migrations.CreateModel(
            name='PhysicalHIW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_link', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Physical HIW',
                'verbose_name_plural': 'Physical HIWs',
            },
        ),
        migrations.CreateModel(
            name='PrizesHIW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_link', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Prizes HIW',
                'verbose_name_plural': 'Prizes HIWs',
            },
        ),
        migrations.CreateModel(
            name='SocialHIW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_link', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Social HIW',
                'verbose_name_plural': 'Social HIWs',
            },
        ),
    ]
