# Generated by Django 5.0 on 2024-02-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('how_it_works', '0005_howitworks_mentalhiw_physicalhiw_prizeshiw_socialhiw'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HowItWorks',
            new_name='GetStarted',
        ),
        migrations.AlterModelOptions(
            name='getstarted',
            options={'verbose_name': 'Get Started', 'verbose_name_plural': 'Get Started'},
        ),
    ]
