# Generated by Django 5.0 on 2024-02-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_it_works', '0006_rename_howitworks_getstarted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgesHIW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_link', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Badges HIW',
                'verbose_name_plural': 'Badges HIWs',
            },
        ),
    ]
