# Generated by Django 5.0 on 2024-02-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_it_works', '0007_badgeshiw'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeshiw',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='getstarted',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mentalhiw',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='physicalhiw',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='prizeshiw',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='socialhiw',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
