# Generated by Django 5.0 on 2023-12-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('company_name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('prize_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_link', models.URLField()),
                ('ig_link', models.URLField()),
                ('tiktok_link', models.URLField()),
                ('twitter_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Daily Prize',
                'verbose_name_plural': 'Daily Prizes',
            },
        ),
    ]
