# Generated by Django 5.0 on 2024-01-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_survey_video_on_app_survey_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='video_on_ig',
        ),
        migrations.AddField(
            model_name='survey',
            name='number_of_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
