# Generated by Django 5.0 on 2023-12-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.CharField(blank=True, max_length=100, null=True, verbose_name='Challenge day')),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Mental Challenge',
                'verbose_name_plural': 'Mental Challenges',
            },
        ),
        migrations.CreateModel(
            name='PhysicalChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.CharField(blank=True, max_length=100, null=True, verbose_name='Challenge day')),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('workout_name', models.CharField(blank=True, max_length=100, null=True)),
                ('required_equipments', models.CharField(blank=True, max_length=100, null=True)),
                ('video_link', models.URLField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Physical Challenge',
                'verbose_name_plural': 'Physical Challenges',
            },
        ),
        migrations.CreateModel(
            name='SocialChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.CharField(blank=True, max_length=100, null=True, verbose_name='Challenge day')),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Social Challenge',
                'verbose_name_plural': 'Social Challenges',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=100, null=True, verbose_name='Challenge day')),
                ('quote', models.TextField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('video_link', models.URLField(blank=True, max_length=250, null=True)),
                ('mental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.mentalchallenge')),
                ('physical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.physicalchallenge')),
                ('social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.socialchallenge')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
            },
        ),
    ]
