# Generated by Django 5.0 on 2024-01-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_instructor_physicalchallenge_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalchallenge',
            old_name='video_link',
            new_name='intense_video',
        ),
        migrations.AddField(
            model_name='physicalchallenge',
            name='level',
            field=models.CharField(blank=True, choices=[('moderate', 'moderate'), ('intense', 'intense')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physicalchallenge',
            name='moderate_video',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
