# Generated by Django 5.0 on 2024-01-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_rename_video_link_physicalchallenge_intense_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalchallenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
