# Generated by Django 5.0 on 2024-01-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_physicalchallenge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
