# Generated by Django 5.0 on 2024-01-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_instructor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentalchallenge',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='socialchallenge',
            name='duration',
        ),
        migrations.AddField(
            model_name='socialchallenge',
            name='voice_recording',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
