# Generated by Django 5.0 on 2024-02-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_remove_socialchallenge_voice_recording_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='physical',
        ),
    ]
