# Generated by Django 5.0 on 2024-02-06 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_remove_challenge_physical'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntensePhysicalChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.CharField(blank=True, max_length=100, null=True, verbose_name='Challenge day')),
                ('description', models.TextField(blank=True, null=True)),
                ('workout_name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('required_equipments', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.URLField(blank=True, max_length=250, null=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.instructor')),
            ],
            options={
                'verbose_name': 'Intense Physical Challenge',
                'verbose_name_plural': 'Intense Physical Challenges',
            },
        ),
        migrations.CreateModel(
            name='ModeratePhysicalChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.CharField(blank=True, max_length=100, null=True, verbose_name='Challenge day')),
                ('description', models.TextField(blank=True, null=True)),
                ('workout_name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('required_equipments', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.URLField(blank=True, max_length=250, null=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.instructor')),
            ],
            options={
                'verbose_name': 'Moderate Physical Challenge',
                'verbose_name_plural': 'Moderate Physical Challenges',
            },
        ),
        migrations.DeleteModel(
            name='PhysicalChallenge',
        ),
    ]
