# Generated by Django 5.0 on 2024-02-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_challenge_intense_physical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='ig_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='tiktok_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
