# Generated by Django 5.0 on 2024-02-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_alter_instructor_ig_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='yt_link',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube link'),
        ),
    ]
